; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5C0E86EA-9010-463B-9945-61413471F294}}
AppName=Gravity Rush 2
AppVersion=1.5
;AppVerName=Gravity Rush 2 1.5
DefaultDirName={autopf}\Gravity Rush 2
DefaultGroupName=Gravity Rush 2
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=Setup
SolidCompression=yes
WizardStyle=modern windows11
DiskSpanning=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\Downloads\DoneDownloading\Games\Gravity rush 2\Gravity_rush_2.arc"; DestDir: "{app}\temp"; Flags: ignoreversion deleteafterinstall
Source: "C:\Program Files (x86)\FreeArc\*"; DestDir: "{app}\temp\FreeArc"; Flags: recursesubdirs createallsubdirs deleteafterinstall
;NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,Gravity Rush 2}"; Filename: "{uninstallexe}"


[Code]

var
  ProgressPage: TOutputProgressWizardPage;
  ProgressFileName: string;

function SetTimer(Wnd, IDEvent, Elapse, TimerFunc: LongWord): LongWord;
  external 'SetTimer@user32.dll stdcall';

function KillTimer(hWnd, uIDEvent: LongWord): BOOL;
  external 'KillTimer@user32.dll stdcall';

procedure UpdateProgressProc(
  H: LongWord; Msg: LongWord; Event: LongWord; Time: LongWord);
var
  S: AnsiString;
  Percent: Integer;
  Pos1: Integer;
begin
  if not FileExists(ProgressFileName) then Exit;

  LoadStringFromFile(ProgressFileName, S);

  if Pos('Extracted', S) > 0 then
  begin
    ProgressPage.SetProgress(100, 100);
    ProgressPage.SetText('Extracted: 100%', '');
    Exit;
  end;

  Pos1 := Pos('%', S);
  if Pos1 > 0 then
  begin
    Delete(S, Pos1, Length(S));
  while (Length(S) > 0) and ((S[Length(S)] < '0') or (S[Length(S)] > '9')) do 
    Delete(S, Length(S), 1);      Delete(S, Length(S), 1);

    Percent := StrToIntDef(S, 0);
    ProgressPage.SetProgress(Percent, 100);
    ProgressPage.SetText(Format('Extracted: %d%%', [Percent]), '');
  end;
end;

procedure ExtractArc;
var
  ArcExtracterPath: string;
  ArcArchivePath: string;
  Cmd: string;
  Timer: LongWord;
  ResultCode: Integer;
begin
  ProgressPage := CreateOutputProgressPage('Installing', 'Extracting game files...');
  ProgressPage.SetProgress(0, 100);
  ProgressPage.Show;

  try
    ArcExtracterPath := ExpandConstant('{app}\temp\FreeArc\bin\Arc.exe');
    ArcArchivePath := ExpandConstant('{app}\temp\Gravity_rush_2.arc');

    if not FileExists(ArcExtracterPath) then
      RaiseException('Arc.exe missing');
     
    if not FileExists(ArcArchivePath) then
      RaiseException('ARC file missing: ' + ArcArchivePath);

    Timer := SetTimer(0, 0, 200, CreateCallback(@UpdateProgressProc));

    Cmd :=Format('"%s" x -y -o+ -dp"%s" "%s"', [ArcExtracterPath,ExpandConstant('{app}'),ArcArchivePath]);

    Log('Running: ' + Cmd);

    if not Exec(
      ArcExtracterPath,
      'x -y -o+ -dp"' + ExpandConstant('{app}') + '" "' + ArcArchivePath + '"',
      ExtractFilePath(ArcExtracterPath),
      SW_HIDE,
      ewWaitUntilTerminated,
      ResultCode
    ) then
    begin
      RaiseException('Failed to start Arc.exe');
    end;

    if ResultCode <> 0 then
    begin
      RaiseException('Extraction failed. Code: ' + IntToStr(ResultCode));
    end;

  finally
    KillTimer(0, Timer);
    ProgressPage.Hide;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    ExtractArc;
  end;
end;
